SECRET_KEY = "seeme"
#
without_redis = false

[redis]
host = "127.0.0.1"
port = 6379
db = 0

[Data_limit_default]
pc = 20
browser = 20
phone = 20

[steam]
enable = false
steam_id = 76561199077836301
steam_key = ""